-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accounts (
  id uuid NOT NULL,
  account_type text CHECK (account_type IS NULL OR (account_type = ANY (ARRAY['user'::text, 'organization'::text]))),
  is_admin boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  url_handle text,
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.blog_reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  blog_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reaction_type text NOT NULL CHECK (reaction_type = ANY (ARRAY['like'::text, 'dislike'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT blog_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT blog_reactions_blog_id_fkey FOREIGN KEY (blog_id) REFERENCES public.blogs(id),
  CONSTRAINT blog_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.blog_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  blog_id uuid NOT NULL,
  session_id text NOT NULL,
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT blog_views_pkey PRIMARY KEY (id),
  CONSTRAINT blog_views_blog_id_fkey FOREIGN KEY (blog_id) REFERENCES public.blogs(id),
  CONSTRAINT blog_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.blogs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content jsonb NOT NULL,
  content_html text,
  author_id uuid,
  author_name text,
  tags ARRAY DEFAULT '{}'::text[],
  abstract text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  admin_comment text,
  is_anonymous boolean DEFAULT false,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  media jsonb,
  featured_image text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  slug text NOT NULL UNIQUE,
  CONSTRAINT blogs_pkey PRIMARY KEY (id),
  CONSTRAINT blogs_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id),
  CONSTRAINT blogs_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.content_saves (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['blog'::text, 'event'::text, 'vacancy'::text])),
  content_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT content_saves_pkey PRIMARY KEY (id),
  CONSTRAINT content_saves_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.content_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['event'::text, 'vacancy'::text])),
  content_id uuid NOT NULL,
  session_id text NOT NULL,
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT content_views_pkey PRIMARY KEY (id),
  CONSTRAINT content_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['training_workshop'::text, 'webinar'::text, 'training_course'::text, 'bootcamp'::text, 'panel_discussion'::text, 'camp'::text, 'forum'::text, 'conference'::text, 'flashmob'::text, 'meetup'::text])),
  event_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  certification jsonb,
  location jsonb NOT NULL,
  application_link text NOT NULL,
  application_deadline timestamp with time zone,
  max_participants integer,
  tags ARRAY DEFAULT '{}'::text[],
  image_url text,
  images jsonb,
  created_by uuid,
  created_by_organization uuid,
  organization_name text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approved_at timestamp with time zone,
  approved_by uuid,
  rejected_at timestamp with time zone,
  rejection_reason text,
  admin_comment text,
  is_published boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  views integer DEFAULT 0,
  unique_views integer DEFAULT 0,
  viewed_by ARRAY DEFAULT '{}'::uuid[],
  engagement_score integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  slug text NOT NULL UNIQUE,
  sessions jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(sessions) = 'array'::text),
  audience_age_min integer CHECK (audience_age_min IS NULL OR audience_age_min >= 0 AND audience_age_min <= 99),
  audience_age_max integer CHECK (audience_age_max IS NULL OR audience_age_max >= 0 AND audience_age_max <= 99),
  requirements ARRAY NOT NULL DEFAULT '{}'::text[],
  participant_benefits ARRAY NOT NULL DEFAULT '{}'::text[],
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT events_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT events_created_by_organization_fkey FOREIGN KEY (created_by_organization) REFERENCES public.accounts(id)
);
CREATE TABLE public.materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  type text NOT NULL,
  url text NOT NULL,
  image_url text,
  provider text,
  duration text,
  language ARRAY DEFAULT '{English}'::text[],
  tags ARRAY DEFAULT '{}'::text[],
  featured boolean DEFAULT false,
  is_published boolean DEFAULT true,
  order integer DEFAULT 0,
  views integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT materials_pkey PRIMARY KEY (id),
  CONSTRAINT materials_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  data jsonb,
  action_url text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.organization_followers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_followers_pkey PRIMARY KEY (id),
  CONSTRAINT organization_followers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization_profiles(account_id),
  CONSTRAINT organization_followers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.organization_profiles (
  account_id uuid NOT NULL,
  organization_name text,
  organization_type text,
  description text,
  email text,
  profile_image jsonb,
  website text,
  contact_phone text,
  address text,
  registration_number text,
  focus_areas ARRAY DEFAULT '{}'::text[],
  contact_person jsonb,
  social_links jsonb,
  moderation_status text NOT NULL DEFAULT 'pending'::text CHECK (moderation_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  admin_comment text,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_verified boolean NOT NULL DEFAULT false,
  slug text NOT NULL UNIQUE,
  url_handle text,
  CONSTRAINT organization_profiles_pkey PRIMARY KEY (account_id),
  CONSTRAINT organization_profiles_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT organization_profiles_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL,
  mongo_id text UNIQUE,
  organization_name text NOT NULL,
  organization_type text NOT NULL,
  email text NOT NULL,
  profile_image jsonb,
  description text NOT NULL,
  website text,
  contact_phone text,
  address text,
  registration_number text,
  focus_areas ARRAY DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approved_at timestamp with time zone,
  approved_by uuid,
  admin_comment text,
  contact_person jsonb NOT NULL,
  social_media jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT organizations_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.site_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  bio text,
  location text,
  website text,
  phone text,
  date_of_birth date,
  gender text,
  occupation text,
  organization text,
  interests text,
  avatar text,
  social_links jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'user'::text CHECK (role = ANY (ARRAY['user'::text, 'admin'::text])),
  auth_provider text NOT NULL DEFAULT 'credentials'::text CHECK (auth_provider = ANY (ARRAY['credentials'::text, 'google'::text])),
  social_media jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.vacancies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  type text NOT NULL,
  category text NOT NULL,
  work_type text NOT NULL,
  location jsonb NOT NULL,
  requirements ARRAY DEFAULT '{}'::text[],
  responsibilities ARRAY DEFAULT '{}'::text[],
  qualifications ARRAY DEFAULT '{}'::text[],
  experience_level text NOT NULL,
  duration jsonb NOT NULL,
  compensation jsonb NOT NULL,
  application_process jsonb NOT NULL,
  application_deadline timestamp with time zone NOT NULL,
  start_date timestamp with time zone,
  skills ARRAY DEFAULT '{}'::text[],
  languages ARRAY DEFAULT '{}'::text[],
  tags ARRAY DEFAULT '{}'::text[],
  image_url text,
  created_by uuid,
  created_by_organization uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approved_at timestamp with time zone,
  approved_by uuid,
  rejected_at timestamp with time zone,
  rejection_reason text,
  admin_comment text,
  is_published boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  is_urgent boolean DEFAULT false,
  application_count integer DEFAULT 0,
  views integer DEFAULT 0,
  unique_views integer DEFAULT 0,
  viewed_by ARRAY DEFAULT '{}'::uuid[],
  engagement_score integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  slug text NOT NULL UNIQUE,
  CONSTRAINT vacancies_pkey PRIMARY KEY (id),
  CONSTRAINT vacancies_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT vacancies_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT vacancies_created_by_organization_fkey FOREIGN KEY (created_by_organization) REFERENCES public.accounts(id)
);