// Article tag options for the application
export const ARTICLE_TAGS = [
  'technology',
  'health',
  'education',
  'environment',
  'social-impact',
  'community',
  'research',
  'policy',
  'innovation',
  'sustainability',
  'human-rights',
  'development',
  'governance',
  'economics',
  'culture',
  'science',
  'agriculture',
  'climate-change',
  'poverty',
  'gender-equality',
  'youth',
  'elderly',
  'disability',
  'mental-health',
  'nutrition',
  'water-sanitation',
  'energy',
  'transportation',
  'housing',
  'employment',
  'entrepreneurship',
  'finance',
  'digital-inclusion',
  'emergency-response',
  'conflict-resolution',
  'peace-building',
  'advocacy',
  'fundraising',
  'volunteer-management',
  'capacity-building'
] as const;


export type ArticleTag = typeof ARTICLE_TAGS[number];