export const siteSettingsDefaults = {
  siteInfo: {
    siteName: 'icma360',
    siteDescription: 'Gənclərin və icmaların inkişafına dəstək platforması',
    siteUrl: 'https://icma360.org',
    contactEmail: 'contact@icma360.org',
    supportEmail: 'support@icma360.org',
    socialLinks: {},
  },
  contentPolicies: {
    requireApproval: true,
    autoApproveVerifiedUsers: false,
    maxArticleLength: 50000,
    maxStoryLength: 10000,
    allowedFileTypes: ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx'],
    maxFileSize: 10,
    moderationKeywords: [],
    bannedWords: [],
    enableProfanityFilter: true,
    enableSpamDetection: true,
  },
  userManagement: {
    allowRegistration: true,
    requireEmailVerification: true,
    defaultUserRole: 'user',
    maxUsersPerDay: 100,
    enableUserSuspension: true,
    suspensionReasons: ['Spam', 'Inappropriate Content', 'Harassment', 'Terms Violation'],
    enableUserDeletion: true,
    dataRetentionDays: 365,
  },
  notifications: {
    enableEmailNotifications: true,
    enablePushNotifications: false,
    emailProvider: 'smtp',
    emailConfig: {},
    defaultNotificationSettings: {
      articleApproved: true,
      articleRejected: true,
      newFollower: true,
      systemUpdates: true,
    },
  },
  security: {
    enableTwoFactor: false,
    sessionTimeout: 1440,
    maxLoginAttempts: 5,
    lockoutDuration: 15,
    enableCaptcha: false,
    captchaProvider: 'recaptcha',
    captchaConfig: {},
    enableRateLimit: true,
    rateLimitConfig: {
      windowMs: 900000,
      maxRequests: 100,
    },
  },
  analytics: {
    enableGoogleAnalytics: false,
    enableHotjar: false,
    enableErrorTracking: true,
    errorTrackingProvider: 'sentry',
    errorTrackingConfig: {},
  },
  performance: {
    enableCaching: true,
    cacheTimeout: 3600,
    enableCompression: true,
    enableCDN: false,
    enableImageOptimization: true,
    imageQuality: 80,
  },
  maintenance: {
    enableMaintenanceMode: false,
    maintenanceMessage: 'Site is under maintenance. Please check back later.',
    enableAutomaticBackups: true,
    backupFrequency: 'daily',
    backupRetentionDays: 30,
    enableDatabaseOptimization: true,
    optimizationSchedule: '0 2 * * 0',
  },
  features: {
    enableComments: true,
    enableLikes: true,
    enableSharing: true,
    enableBookmarks: true,
    enableFollowing: true,
    enableCollaboration: false,
    enableVersioning: false,
    enableAI: false,
    enableTranslation: false,
  },
  api: {
    enablePublicAPI: false,
    requireAPIKey: true,
    rateLimitPerHour: 1000,
    enableWebhooks: false,
    webhookEndpoints: [],
  },
} as const;
